name: Deploy
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t vijayvardhanreddy/hprofile
    - run: echo "${{secrets.DOCKER_TOKEN}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin 
    - run: docker push vijayvardhanreddy/hprofile:latest