name: hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
# now we can write our maven test command, maven checkstyle
# first step is to clone the source code "code checkout"
      - name: code checkout
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test
    
      - name: checkstyle
        run: mvn checkstyle:checkstyle

# setup java 11 to be default (sonar-scanner requirement as of 5.x)
      - name: set java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

# scan our source code with sonarQube scanner and later will upload all this result to sonar cloud 
# sonarcloud is a cloud based platfom used for continuous code quality inspection and code analysis.
      # Setup sonar-scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      # Run sonar-scanner
      - name: SonarQube Scan
        run: sonar-scanner
            -Dsonar.host.url=${{ secrets.SONAR_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.sources=src/
            -Dsonar.junit.reportspath=target/surefire-reports/
            -Dsonar.jacoco.reportspath=target/jacoco.exec
            -Dsonar.java.checkstyle.reportpaths=target/checkstyle-result.xml

